DB_NAME = 'Stock_Project_DB';
USER_EDITOR_ROLE = 'editor';
USER_DEFAULT_ROLE = 'user';
USER_ROLES = [USER_DEFAULT_ROLE, USER_EDITOR_ROLE];

module.exports = {
    DB_NAME,
    USER_ROLES,
    USER_EDITOR_ROLE,
    USER_DEFAULT_ROLE,
};
